### PR TITLE
Expose Select component

### PR DESCRIPTION
**Pull request by lucasmotta**
I need it for the Composer component - for now I created a copy of the component locally, but it would be great if I can could reuse it from the design-system package.

### CODE REVIEW

**Comment by peduarte** [comment]
@colmtuite can I merge and release? Looks like @lucasmotta needs this component

**Comment by colmtuite** [comment]
Yep sure. We're still a couple weeks away from having the proper Select

**Review by colmtuite — APPROVED** [review]

**Comment by lucasmotta** [comment]
Cool, I also just upgraded stitches to the latest canary, but TS is complaining now - I will see what I can do to fix that, otherwise I will reverse the stitches version.

**Pull request closed without merging**
